### PR TITLE
adapter for iOS7

### PR DESCRIPTION
**Pull request by answer-huang**
adapter for iOS7's statusBar。

### CODE REVIEW

**Comment by HanClinto** [comment]
This works perfectly for me, thanks!  I was having trouble with an unusable (blank) 20 pixel bar at the bottom of my screen in iOS7 when using MGSplitViewController, and this fixed me problem.  

Thanks so very very much!

**Comment by hokster7** [comment]
Is this issue still open then?

**Comment by HanClinto** [comment]
It was still an issue for me, yes.  My problems with iOS7 weren't fixed until I used this patch.

**Comment by answer-huang** [comment]
It seems that the auth has not update this response for a long time.

**Pull request closed without merging**
